# Generated by Django 3.1.1 on 2020-09-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nRegistro', models.CharField(max_length=12, unique=True, verbose_name='Numero de Registro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('razonSocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon Social')),
                ('nit', models.CharField(max_length=18, verbose_name='NIT')),
                ('actEcon1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad Economica 1')),
                ('actEcon2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad Economica 2')),
                ('actEcon3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad Economica 3')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nRegistro', models.CharField(max_length=12, unique=True, verbose_name='Numero de Regisro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nit', models.CharField(blank=True, max_length=18, null=True, verbose_name='NIT')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('tipo', models.IntegerField(verbose_name='Tipo de Libro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controliva.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaContribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(verbose_name='Correlativo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nComprobacion', models.IntegerField(blank=True, null=True, verbose_name='Numero de Comprobacion')),
                ('serie', models.IntegerField(blank=True, null=True, verbose_name='Serie')),
                ('corrIntUni', models.IntegerField(blank=True, null=True, verbose_name='Correlativo Interno Unico')),
                ('venExentas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Exentas')),
                ('venGravadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Gravadas')),
                ('ivaDebFiscal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Debito Fiscal')),
                ('vtVentas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Terceros Ventas')),
                ('vtIVA', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Terceros IVA')),
                ('ivaRetenido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Retenido')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
                ('ventasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas No Sujetas')),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controliva.empresa', verbose_name='Contribuyente')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controliva.libro')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaConsumidorFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativoInicial', models.IntegerField(verbose_name='Correlativo Inicial')),
                ('correlativoFinal', models.IntegerField(verbose_name='Correlativo Final')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('exento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exento')),
                ('locales', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Locales')),
                ('ventaTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Venta Total')),
                ('ventaCtaTerceros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Venta Cta Terceros')),
                ('exportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exportaciones')),
                ('ventasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas No Sujetas')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controliva.libro', verbose_name='Libro')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(verbose_name='Correlativo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cExenteInterna', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Exenta Interna')),
                ('cExenteImportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Exenta Importaciones')),
                ('cGravadaInterna', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Gravada Interna')),
                ('cGravadaImportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Gravada Importaciones')),
                ('ivaCdtoFiscal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Cdto Fiscal')),
                ('totalCompra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Compra')),
                ('retencionPretencion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Retencion Pretencion')),
                ('anticipoCtaIva', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Anticipo Cta IVA')),
                ('ivaTerceros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Iva Terceros')),
                ('comprasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compras No Sujetas')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controliva.empresa')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controliva.libro')),
            ],
        ),
    ]
