# Generated by Django 3.1.1 on 2020-09-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controliva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Acivo'), (2, 'Pasivo'), (3, 'Capital')], verbose_name='Tipo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cuenta_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='LibroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controliva.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Libro Diario',
                'verbose_name_plural': 'Libros Diarios',
            },
        ),
    ]
