# Generated by Django 3.1.1 on 2020-09-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controliva', '0001_initial'),
        ('general', '0002_auto_20200916_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controliva.cliente', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Catalogo de Cuentas',
                'verbose_name_plural': 'Catalogos de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='CuentaPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('monto', models.FloatField(blank=True, null=True, verbose_name='Monto')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cuenta Principal',
                'verbose_name_plural': 'Cuentas Principales',
            },
        ),
        migrations.CreateModel(
            name='DiarioMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controliva.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Libro Diario Mayor',
                'verbose_name_plural': 'Libros Diario Mayor',
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('monto', models.FloatField(blank=True, null=True, verbose_name='Monto')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.subcuenta', verbose_name='Cuenta Padre')),
                ('cuenta_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cuentaprincipal', verbose_name='Cuenta Principal')),
            ],
            options={
                'verbose_name': 'Subcuenta',
                'verbose_name_plural': 'Subcuentas',
            },
        ),
        migrations.RenameModel(
            old_name='LibroDiario',
            new_name='AuxiliarDiarioMayor',
        ),
        migrations.AlterModelOptions(
            name='auxiliardiariomayor',
            options={'verbose_name': 'Libro Auxiliar Diario Mayor', 'verbose_name_plural': 'Libros Auxiliar Diario Mayor'},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='subcuenta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='general.subcuenta', verbose_name=''),
            preserve_default=False,
        ),
    ]
