# Generated by Django 3.1.1 on 2020-09-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200917_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaprincipal',
            name='catalogo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='general.catalogocuentas', verbose_name='Catalogo de Cuentas'),
            preserve_default=False,
        ),
    ]
