# Generated by Django 3.1.1 on 2020-09-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200921_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaprincipal',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='subcuenta',
            name='monto',
        ),
    ]
