# Generated by Django 3.1.1 on 2020-09-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200922_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('libro_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.auxiliardiariomayor', verbose_name='Libro Auxiliar')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='partida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='general.partida', verbose_name='Partida'),
            preserve_default=False,
        ),
    ]
